exported fortune teller states as SVG from Figma
cse110-sp23-group1/Origami-Fortune-Teller pull request #19
Opened 2023-05-16 18:14 UTC by lmeiucsd

SVG files are in assets/icons. I created placeholder descriptive naming conventions for the SVG file names for now.

One issue is that the SVG files have a lot of empty space at the bottom of the area:
<img width="218" alt="Screen Shot 2023-05-16 at 11 09 16 AM" src="https://github.com/cse110-sp23-group1/Oragami-Fortune-Teller/assets/88351375/3cac9c7d-28a1-431c-8b2e-e7ee6c305201">

2023-05-16 18:24 UTC, phentos commented
We don't need to merge this branch until the fortune teller is functional (which likely won't be for another week) so I'm converting the PR to draft, but I'll make an issue to clean up the SVGs

2023-05-16 19:02 UTC, lmeiucsd commented
above commit is working on #20 as well as renaming the folder that stores the SVGs to 'origami'

2023-05-30 18:16 UTC, phentos requested changes
Flatten the SVG directories and get rid of the old versions -- there are currently almost 40 files, with almost all of them being unused.

We also should consider identifying the path changes between states and just apply those directly instead of hardcoding every svg variant

2023-05-30 18:16 UTC, phentos commented on assets/scripts/main.js
> +const verticalSVG = new Origami(svgPaths[4]);
Why are there multiple instances of `Origami` ? There is only one fortune teller, so there should only be one class. Move the state tracking of the svg into its state handler (the Origami class).

2023-05-30 18:16 UTC, phentos commented on assets/scripts/main.js
> +        startAnimation(numAnimations);
It's hard to tell from the code, but it seems this is trying to tell what number the flap had in order to open and close the fortune teller that many times. If so, this approach seems very overengineered to me -- couldn't the click event call the animator and pass in the number directly?

Side note -- all of this belongs in the class itself

2023-05-30 18:16 UTC, phentos commented on assets/scripts/main.js
> +let CURRENTSVG = closedSVG;
aren't we using `CAPITALIZED_NAMES` for constants? also, the class tracks / can track the current SVG, so there isn't a reason to have a global variable in main for it

2023-05-30 18:16 UTC, phentos commented on assets/scripts/main.js
> +function startAnimation(numAnimations) {
This function belongs in the class, not in main

2023-05-30 18:16 UTC, phentos commented on assets/scripts/main.js
> +    function animate() {
Give `animate` a proper function block, putting an async recursive function inside an anonymous function generating promises is brain-melting. For an example of how to more cleanly deal with promises, check out how i set them up for [the magic 8ball shakes](https://github.com/phentos/johnnymagic/blob/6c9208d2da89bca6dc0bd0072465be1ac25d24da/magic8ball.js#L239).

2023-05-30 18:16 UTC, phentos commented on assets/scripts/main.js
> +            break;
I'm allergic to `switch` in general, but to put it in more general terms why this isn't a good use case let's look at what it's doing.

- Given `CURRENTSVG`, check which type it is
- no matter what, call `removeCurrentSVG` on it (which is odd since "currentSVG" should already know what is current, right?)
- no matter what, set it to the opposite type

Since we're doing the same things no matter what, it isn't a `switch` at all. Instead consider moving this into a function that does the `no matter whats` -- ie, it swaps the current SVG style.

2023-05-30 18:16 UTC, phentos commented on assets/scripts/main.js
> +          }
Similar situation to above -- we don't actually have any uncertainty about the next required state which would require a check. Always remove, always set the final type swapped.

2023-05-30 18:16 UTC, phentos commented on assets/scripts/main.js
> + * Handles logic for the front-end animation of the fortune teller.
Since we're alternating between two states some number of times, we should just abstract the sequence. As in, given the animation is swapping `{horizontal, vertical}` however many times and then ending on some other state, why not set that up directly without any conditionals?

2023-05-30 18:16 UTC, phentos commented on assets/scripts/main.js
> +let animationCount = 0;
Why is this a global? Just call the animation function with the demanded number, and it can handle it locally.

2023-05-30 18:16 UTC, phentos commented on assets/scripts/Origami.js
> +};
i converted these as a placeholder just to get them out of switch case, but this should be done cleaner; like couldn't we get the color from the click event itself? why do we need to look it up after the fact?

2023-05-30 18:16 UTC, phentos commented on assets/scripts/Origami.js
> +    const svg = document.createElement('object');
why is this an `object` and not an `svg` ?

2023-05-30 18:16 UTC, phentos commented on assets/scripts/Origami.js
> +    document.body.appendChild(svg);
the class shouldn't be appending anything -- just give it back and let the caller decide where it goes

2023-05-30 18:16 UTC, phentos commented on assets/scripts/Origami.js
> +  }
i'm not sure why we're removing the stored SVG at all -- why not just replace the paths that need to change to get to the next state?

2023-05-30 18:16 UTC, phentos commented on assets/scripts/Origami.js
> +  }
Isn't the color of a flap in the SVG itself? Why do we need a lookup at all?

2023-05-30 18:16 UTC, phentos commented on assets/scripts/Origami.js
> +  }
Same as previous comment, the number is in the flap itself, so why do we need to look it up? I wrote about the number rendering [on slack](https://cse110team1.slack.com/archives/C0532PPASKE/p1685074449426429) a few days ago

2023-05-30 18:16 UTC, phentos commented on assets/scripts/Origami.js
> +  }
these functions are identical aside from the query selector, but I'm fairly sure even that difference could be eliminated. These should be one function. I'm also not sure why this this needs to wait for load and be asynchronous? Why isn't it sufficient to just add the click listeners?

2023-06-01 01:22 UTC, adarsh249 commented
Please check the code now. Also, we put the sidebar on here for the status video and ended up writing some code about it anyways (hiding it when we animate, saving fortunes on first click, fetching fortunes from localStorage & displaying them at the end), so let us know if we need to remove that for this branch.

2023-06-01 23:24 UTC, parth4apple reviewed
Looks good! Just one small thing:
1. When you hover over the text of the number, you can not click the fortune flap to go to the next step. This can be fixed by putting `pointer-events: none` on the text element that contains the number.

2023-06-02 01:03 UTC, parth4apple approved these changes
lgtm

2023-06-02 04:07 UTC, merged