Dimension fixes
cse110-sp23-group1/Origami-Fortune-Teller pull request #91
Opened 2023-06-09 18:53 UTC by samw0627

2023-06-10 18:46 UTC, adarsh249 commented
Perfect, may this be last major code change we have

2023-06-10 18:47 UTC, adarsh249 approved these changes, later dismissed
tested, works on small and bigger screens fine, cursor bug fixed and synced w main

2023-06-10 20:27 UTC, parth4apple requested changes

2023-06-10 20:27 UTC, parth4apple commented on assets/styles/main.css
>  }
The changes to `.sidebar` broke the mobile view of the page.


<img width="774" alt="Screenshot 2023-06-10 at 1 22 52 PM" src="https://github.com/cse110-sp23-group1/Origami-Fortune-Teller/assets/72187062/0ba3c276-1b45-43f3-b869-9cc2296c8b8a">

2023-06-10 20:27 UTC, parth4apple commented on assets/styles/main.css
On screens that are not as tall, fortune boxes get cut off. This can be fixed by maybe shrinking the size of the `object` element through a media query. Something like:
`media screen and (max-height:900px){ width: <smaller width>  }`

<img width="2055" alt="Screenshot 2023-06-10 at 1 24 23 PM" src="https://github.com/cse110-sp23-group1/Origami-Fortune-Teller/assets/72187062/b7475741-b767-4825-9cce-f3be7d51ec32">

2023-06-10 22:52 UTC, samw0627 commented on assets/styles/main.css
I think if you scroll down the fortunes boxes should be there

2023-06-10 23:42 UTC, parth4apple commented on assets/styles/main.css
True. There is still wasted space at the top but we can leave it like this since we are tight on time.

2023-06-10 23:43 UTC, samw0627 commented on assets/styles/main.css
I tried resizing the origami and it messed up the position of the fortunes

2023-06-11 00:01 UTC, parth4apple commented on assets/styles/main.css
I think its fine if the end fortune is a little off of the flap. That is better than having whitespace at the bottom and having our page be scrollable.

2023-06-11 00:07 UTC, parth4apple approved these changes
lgtm

2023-06-11 00:08 UTC, christiansulaiman approved these changes
looks good to me.

2023-06-11 00:12 UTC, merged